### ISSUE TITLE
Want me to take this over?

### ISSUE THREAD

**Issue by rathboma** [sqlectron/sql-query-identifier#1]
Not sure how easy this is, but any interest in transferring this to the beekeeper-studio org? I'm using it and will need to extend it anyway

**Comment by rathboma** [comment]
@maxcnunes ping on this - I have improvements I want to make, happy to keep up the NPM package if you transfer that to me also

**Comment by maxcnunes** [comment]
hey @rathboma sorry for the delay. I am back working on sqlectron, so I rather keep it under that org. I can give you access to the npm and github project.

**Comment by maxcnunes** [comment]
What is your npm username?

**Comment by MasterOdin** [comment]
Hey @rathboma, so with this repo under sqlectron, I'm also looking to probably make some changes to expand functionality (like having views and functions detected by create / drop types). Let's hopefully coordinate through issues and PRs on this!

**Comment by rathboma** [comment]
My npm username is `rathboma`. Pretty much that's me everywhere online.

**Comment by MasterOdin** [comment]
I've added you on NPM. However, I would greatly advocate for just going through the process to update NPM of cutting a new release on GitHub with appropriate changelog entry under it, and then letting the [GH publish workflow](https://github.com/sqlectron/sql-query-identifier/blob/master/.github/workflows/publish.yml) handle then pushing to NPM.

I think at this point, we can safely close this issue?

**Comment by rathboma** [comment]
Yes, that's exactly how it should work.
