### ISSUE TITLE
Add support for schema statements

### ISSUE THREAD

**Issue by MasterOdin** [sqlectron/sql-query-identifier#36]
* CREATE SCHEMA
* DROP SCHEMA
* ALTER SCHEMA

These statement types are missing.

**Comment by MasterOdin** [comment]
@rathboma For mysql, the above statements are all aliases for `DATABASE`, e.g. `CREATE SCHEMA` is an alias for `CREATE DATABASE`. Given the mysql dialect, should we then return `CREATE_DATABASE` instead of `CREATE_SCHEMA` given that `CREATE_SCHEMA` is not equivalent to what the statement type means in other DBs given the usual tree based structure for displaying a given DB server.

**Comment by rathboma** [comment]
I think that could be more confusing honestly so I'd probably just do the naive thing.

I think mostly folks will be looking out for the type of statement rather than the explicit type anyway.
